# Generated by Django 5.0.3 on 2024-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Article', 'verbose_name_plural': 'historical Articles'},
        ),
        migrations.AlterModelOptions(
            name='historicalgrouparticles',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Group Article', 'verbose_name_plural': 'historical Group Articles'},
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgrouparticles',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
